### ISSUE TITLE
error when merging a PR with NO ENTRY for release notes

### ISSUE THREAD

**Issue by smichr** [sympy/sympy-bot#10]
The error message was: Command '['git', 'commit', '-m', 'Update Release-Notes-for-1.2.1.md from PR #14870']' returned non-zero exit status 1.

**Comment by asmeurer** [comment]
Thanks for opening the issue. It should be fixed by https://github.com/sympy/sympy-bot/commit/c795779917e1d2f84019a41740261f8233ed7395. Let's wait until another PR with `NO ENTRY` is merged to make sure.

**Comment by asmeurer** [comment]
Here's another pull request where it worked fine.
