### ISSUE TITLE
Difficult to get the correct release notes.

### ISSUE THREAD

**Issue by Peter230655** [sympy/sympy-bot#108]
It seems, it is very difficult to get sympy-bot to accept a release note.
All I di was trying to make a small change in kane.py, which is found at sympy/physics/mechanics.
No matter what I tried it would not accept it. It kept on saying the was no subheader, but I copied exactly (or so I thought) the examples given.

It says one should give release notes- but I could not find examples of how to do it.
Finally I tried this:
```
Sympy 1.14dev
* physics.mechanics
  * remove reaction forces
 ```
but still it could find no subheader.
Now my PR is stuck, it is #27129
**Any help is GREATLY appreciated!**

**Comment by asmeurer** [comment]
Where is the SymPy PR for this? 

You need to have the `<!-- BEGIN RELEASE NOTES -->` section. If you kept the PR template intact it should already be there.

**Comment by Peter230655** [comment]
> Where is the SymPy PR for this?
> 
> You need to have the `<!-- BEGIN RELEASE NOTES -->` section. If you kept the PR template intact it should already be there.

I finally managed - and in retrospect I think, I just did not follow the examples verbatimly!
(I closed the PR in the meantime, as I was trying to solve a non-existant problem.)
**Thanks for your reply!**
