### ISSUE TITLE
Ready for testing

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot#2]
This is now ready for testing. I have it set up on my test repo at https://github.com/asmeurer/GitHub-Issues-Test. Please make a pull request against that repo and test writing release notes in the PR description. I can give you push access to that repo if you want to test merging. 

You can see an example at https://github.com/asmeurer/GitHub-Issues-Test/pull/31, which got added to https://github.com/asmeurer/GitHub-Issues-Test/wiki/Release-Notes-for-1.2.1

I still need to improve the messaging (suggestions welcome), but the bot behavior itself should be working and complete now.

CC @certik (and anyone else who wants to test it)

**Comment by certik** [comment]
Ok, I tested it in https://github.com/asmeurer/GitHub-Issues-Test/pull/32 and based on that I created #3. Otherwise I think it seems to work great.

**Comment by certik** [comment]
Also created #4 and #5.

**Comment by asmeurer** [comment]
@certik I gave you push access if you want to test merging.

**Comment by certik** [comment]
I still don't have merge access at https://github.com/asmeurer/GitHub-Issues-Test/pull/32.

**Comment by asmeurer** [comment]
Oops, I accidentally gave you access on this repo. You should have access now once you accept the invite.

**Comment by certik** [comment]
Ok. I think it works.

**Comment by asmeurer** [comment]
OK, this is ready for round 2 testing. I've updated the text in the comments. You can test it at https://github.com/asmeurer/GitHub-Issues-Test/pull/35 (or create your own PR). I also added some features that were missing (multiline release notes, and multiple authors). Let me know if you have any suggestions on the comment text.

I plan to make a PR to SymPy updating the PULL_REQUEST_TEMPLATE tomorrow, so we can get this deployed.

**Comment by certik** [comment]
I suggest to fix https://github.com/sympy/sympy-bot/issues/4. Otherwise I think it looks good.

**Comment by asmeurer** [comment]
@certik can you sign up for Heroku and let me know which email you used, so I can give you access as well.

**Comment by asmeurer** [comment]
OK, let's move all the testing discussion over to https://github.com/sympy/sympy/pull/14942. Please open new issues or pull requests here if you have any suggestions for the bot.
