### ISSUE TITLE
is the initial reply too scary?

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy-bot#23]
A fair number of people are opening PRs and then closing them, only to post later with a new PR.  I guess its because a big red x appears.  Maybe we can soften the text in the failed case:

- - - -

Hi, I am the SymPy bot (vxyz). I'm here to make sure this pull request has a release notes entry.

There was an issue with the release notes.  The `<!-- BEGIN RELEASE NOTES -->` block was not found.    No need to open a new pull request; you can edit the text above.  Please read the ...

[triangle thing] click.

Note: this comment will be updated ....

**Comment by cbm755** [comment]
"Hi, I am the SymPy bot.  I'm here to help you write a release notes entry."

....

**Comment by asmeurer** [comment]
So to clarify, the suggestion is to:

- Remove the emojis (or just remove the :X: emoji?).
- Add text that says you can edit the description if it failed. 

Anything else?

**Comment by cbm755** [comment]
* Maybe move the emoji later so its not the first thing?
* add text that says you can edit the description, perhaps explicitly telling folks not to close the PR
* "I'm here to help you" instead of "I'm here to make sure".

Here's my attempt at what the failure text could be:
- - - -

Hi, I am the SymPy bot (v124). I'm here to help you write a release notes entry.

:x:   There was an issue with the release notes: the `<!-- BEGIN RELEASE NOTES -->` block was not found.  **Please do not close this pull request;** instead edit the description after reading the [guide on how to write release notes](https://github.com/sympy/sympy/wiki/Writing-Release-Notes).

Note: This comment will be updated if you edit the pull request. You may need to reload the page to see it.

[triangle] Click here to see the pull request description that was parsed.

**Comment by certik** [comment]
@cbm755 I like that.
