### ISSUE TITLE
Check against <!-- BEGIN RELEASE NOTES --> being in commit messages

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot#27]
Some people have been putting `<!-- BEGIN RELEASE NOTES -->` in their commit messages. I wonder if we should check for this and warn, or even fail if it is the case.

**Comment by certik** [comment]
Is it possible to check? If so, then definitely, ask provide instructions how to remove it from the git log.

**Comment by asmeurer** [comment]
Yes, sure it's very easy. We already download the commit data to get the authors so it wouldn't even be more API calls. 

The question is just, should do it, and if we do, what messaging do we do, and should it fail the build?

**Comment by certik** [comment]
If it's easy, then I would warn the user that the release notes should be put in the PR description, not the commit log, and ask to fix it.

Regarding failing the build --- I don't know. I am leaning towards failing the build.
