### ISSUE TITLE
When the release notes fail, add a link to how to write release notes

### ISSUE THREAD

**Issue by certik** [sympy/sympy-bot#3]
Currently when the release notes fail, it's not clear for me how to fix it, the added hints are nice, but not good enough. In addition what it says, let's add a sentence:
```
For more information please consult how to write release notes [here](...).
```
And on that page, let's document exactly what is allowed and not allowed and what is expected about good release notes.

**Comment by asmeurer** [comment]
Yep, I plan on writing a wiki page on how to write release notes. And I am also planning to rewrite most of the text from the bot to be more helpful. We will probably need to iterate on it regardless, after we deploy it and see what people do and don't get.

**Comment by certik** [comment]
I agree.

**Comment by asmeurer** [comment]
Here's the wiki page I wrote (I am still working on improving the text from the bot itself). Let me know if you have any suggestions, and feel free to edit it. https://github.com/sympy/sympy/wiki/Writing-Release-Notes

**Comment by certik** [comment]
I think this is good. Make sure the bot links to it in the comment.
