### ISSUE TITLE
Too many NO ENTRY

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot#30]
One issue I've noticed with the bot is that people write NO ENTRY for pull requests that really should have a release note entry. 

I'm not really sure what to do about this. This is what it says in the [pull request template](https://raw.githubusercontent.com/sympy/sympy/master/PULL_REQUEST_TEMPLATE.md)

```markdown
#### Release Notes

<!-- Write the release notes for this release below. See
https://github.com/sympy/sympy/wiki/Writing-Release-Notes for more information
on how to write release notes. If there is no release notes entry for this PR,
write "NO ENTRY". The bot will check your release notes automatically to see
if they are formatted correctly. -->

<!-- BEGIN RELEASE NOTES -->

<!-- END RELEASE NOTES -->
```

Maybe the issue is that it is mentioned there? If anyone has any suggestions on how this can be improved let me know.

**Comment by asmeurer** [comment]
I'm thinking of removing the references to NO ENTRY from the PULL_REQUEST_TEMPLATE as well as from the sympy-bot messages, and having it only be in the [guide](https://github.com/sympy/sympy/wiki/Writing-Release-Notes) (which describes the conditions for which NO ENTRY should be used).

**Comment by cbm755** [comment]
I agree, this will slightly push the task of changing to NO ENTRY onto reviewers: that's probably a good thing.

**Comment by asmeurer** [comment]
OK, removed from the PR template at https://github.com/sympy/sympy/pull/15168 and from the bot messages at https://github.com/sympy/sympy-bot/pull/33.
