### ISSUE TITLE
Add a text

### ISSUE THREAD

**Issue by certik** [sympy/sympy-bot#4]
Add a text that the same comment will be updated by the bot. I was looking for a new comment, and it took me a while to realize that the bot updated the same comment.

**Comment by asmeurer** [comment]
There is some text at the bottom of the comment to this effect, but I will try to make it more clear. Unfortunately, GitHub doesn't update the comment unless you reload the page.

**Comment by asmeurer** [comment]
I now have this in bold at the bottom. Let me know if you think the wording can be improved.

**Comment by certik** [comment]
Right now it says:

> Note: If you edit the pull request description, you need to reload the page
to see my latest status check!

Rather, I suggest it says:

> Note: This comment will be updated with the latest check if you edit the pull request. You need to reload the page to see it.

It doesn't need to be bold I think.
