### ISSUE TITLE
Release notes entry for patches against release branch

### ISSUE THREAD

**Issue by sidhantnagpal** [sympy/sympy-bot#58]
It looks like the patches made against the release branch, will have their release notes entry added to the wiki page of the next release (and not the current release). This came to my attention in https://github.com/sympy/sympy/pull/16408.

For the patch https://github.com/sympy/sympy/pull/16408 (made against the 1.4 branch) the bot says that "This will be added to https://github.com/sympy/sympy/wiki/Release-Notes-for-1.5".

**Comment by asmeurer** [comment]
The bot should be getting the version from the release file in the base branch of the PR. I'll have to investigate why this is wrong. 

If that PR is merged in the meantime please correct the wiki.

**Comment by asmeurer** [comment]
Oh actually looking more closely at the code maybe it's not actually doing that. The contents_url is just based on the repo, which I guess uses the default branch.

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/pull/16408 is showing the right URL now. We can double check when it is merged that it goes in the right file.
