### ISSUE TITLE
some way to indicate major/minor changes?

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy-bot#9]
Maybe I missed it?

I'm sure at some point there are diminishing returns, and of course a human can tweak the wiki later.  But it just seems like a pain for a human being to decide *later* which of the many changes are major and which are minor.

**Comment by asmeurer** [comment]
We were originally going to do major and minor, but when I hand compiled the [release notes for 1.2](https://github.com/sympy/sympy/wiki/Release-Notes-for-1.2), I noticed that it made more sense to organize the notes by submodule. It wasn't always clear when a change was major or minor. You can even see the "minor" changes at the bottom from when I started to do that, but it ultimately doesn't make sense. Basically, any truly "minor" change doesn't go in the release notes at all (like docs changes or non-user facing changes). 

There are "highlights" at the top of the release notes, which are hand compiled (see https://github.com/sympy/sympy/wiki/Writing-Release-Notes#highlights). Those could be considered the "major" changes and everything else is "minor".

**Comment by asmeurer** [comment]
With that being said, I'm open to suggestions. My number 1 priority is getting people to write the notes. As long as people are doing that, I don't care as much how they are formatted, as long as they are of a certain quality (e.g., we could just list the merged PRs in the notes, but that isn't very high quality compared to hand written notes).
