### ISSUE TITLE
SymPy bot error in merging release notes

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy-bot#94]
SymPy bot gives error in https://github.com/sympy/sympy/pull/20734 

The PR that I have merged was https://github.com/sympy/sympy/pull/20738 which had correct release notes, but https://github.com/sympy/sympy/pull/20734 was also merged automatically which had bad release notes.

**Comment by asmeurer** [comment]
Ah yes, this is a known issue https://github.com/sympy/sympy-bot/issues/56. You can ignore the error.
